version: "3"
services:
  server:
    build: ./server
    ports:
      - "0.0.0.0:5000:3000"
    volumes:
      - /app/node_modules
      - ./server:/app
    command: npm start
  client:
    build: ./streamy
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - /app/node_modules
      - ./streamy:/app
    command: npm start
